### PR TITLE
Add build options for Windows

### PR DESCRIPTION
**Pull request by shoubhikraj**
This PR aims to make xtb4stda compilable on Windows.

Fixed some command line calls from within Fortran code, and changed the meson build script to provide correct compiler arguments for Intel Fortran on Windows.

The command line calls are guarded with `#if defined`, so preprocessing is turned on during compiling.

### CODE REVIEW

**Comment by mdewergi** [comment]
As for stda windows version, we will test it and get back to you as soon as possible. @pierre-24 You know what to do.

**Comment by pierre-24** [comment]
Same comment: that works, but I would remove `traceback` :)

**Comment by shoubhikraj** [comment]
@pierre-24 I have made the traceback option available only for debug build. Does that work?

**Comment by mdewergi** [comment]
Yep for me it is. I will merge everything next week (xtb4stda and stda) because I have an updated version of stda with a few new features to merge as well. So I would like to do everything at the same time.
Many thanks to you both,
Marc

**Pull request merged**
