### PR TITLE
Allow dynamic compilation

### PR DESCRIPTION
**Pull request by pierre-24**
As usual, I need dynamic compilation in order to compile on our cluster.

Tested with Intel 2018, works perfectly.

### CODE REVIEW

**Comment by pierre-24** [comment]
(I would be happy to add a test somewhere if needed)

**Comment by mdewergi** [comment]
Hi Pierre,
This seems reasonable but since static was the default compilation, can you not do the reverse and put a dynamic flag that comments the line instead?

**Comment by pierre-24** [comment]
Don't worry, that's still the case: since the defaut is `-Dstatic=true`, even if not explicitelly set, so the old behaviour remains. In fact, this is just a copy/paste [from `stda`](https://github.com/grimme-lab/stda/blob/master/meson.build#L30-L32) (and `xtb`, before the file was completely remodelled)

**Comment by mdewergi** [comment]
Ok good

**Pull request merged**
