### PR TITLE
Adds missing `gfnver` argument for xbasis function.

### PR DESCRIPTION
**Pull request by Zymergen-jvandezande**
I needed this change to make things run. I would recommend that someone confirm this is correct since I am unexperienced in Fortran and this codebase, and could not find any unit tests to run this against.

### CODE REVIEW

**Comment by mdewergi** [comment]
gfn version is not available in this code because xtb4stda is a specially designed method for excited states that has different Hamiltonian, basis set, and parameterization than GFN-type methods. Thus, that does not make any sens to include it. Could you explain why you need this in the code?

**Comment by Zymergen-jvandezande** [comment]
The subroutine `xbasis` on ie 23 in `xbasis.f` is defined as:

```
subroutine xbasis(n,at,nbf,coord,q,cn,
.           zqf,zcnf,split,ok,diff,runtyp,gfnver)
```

In order to get things to compile, I need to add the gfnver argument. I am unfamiliar with this codebase and Fortran, but it refused to compile until I made this change, giving me the error:

```
  533 |      .             zqf,zcnf,split,okbas,diff,runtyp)
      |                                                                        1
Error: Missing actual argument for argument ‘_formal_54’ at (1)
ninja: build stopped: subcommand failed.
```

**Comment by mdewergi** [comment]
Ok I see, it is just for compilation purpose. What compiler are you using? This is an optional argument, normally it should compile.

What do you think Sebastian @awvwgk ? You are more familiar than me with the code. This looks to me safe.

**Comment by awvwgk** [comment]
`gfnver` shouldn't be referenced, leaving away the argument in an implicit interface is indeed wrong and a compile time error. So this fix looks fine.

**Pull request merged**
